_WD_GetElementFromPoint()  - fix for Au3Check
Danp2/WebDriver pull request #114
Opened 2021-12-30 14:11 UTC by mlipok

#forceref $bFrame

2021-12-30 15:00 UTC, Danp2 commented
Can you explain why Au3check flags this variable? It's not making sense to me.

2021-12-30 15:13 UTC, Danp2 commented
I guess simply assigning a value to the variable isn't enough to pass the usage test. Originally, I had planned to include the following near the end of the function --
```
; Exit to top-most window
If $bFrame Then
	$sResponse = _WD_Window($sSession, "frame", '{"id":null}')
EndIf
```

That code is commented out because I believe the element ID being returned value outside of the current browsing context. I'm thinking it would be good to change last line to this so that the calling routine can check @extended to determine if the browsing context was changed --
```
	Return SetError($_WD_ERROR_Success, $bFrame, $sElement)
```

This would eliminate the need for the #forceref as well.

2021-12-30 19:58 UTC, Danp2 requested changes
Can you take a look at the changes that I just added to this PR and give your feedback?

2021-12-30 20:11 UTC, mlipok commented
Yes in next few hours

2021-12-31 12:33 UTC, Danp2 approved these changes

2021-12-31 12:35 UTC, Danp2 commented
@mlipok Did you get a chance to review my changes?

2021-12-31 12:51 UTC, mlipok commented
> @mlipok Did you get a chance to review my changes?

![image](https://user-images.githubusercontent.com/11089482/147824353-eb9e7a31-d5b7-4975-8f71-bd0baf0ef88e.png)

2021-12-31 13:19 UTC, Danp2 commented
@mlipok I think you need to finalize your review so that it is no longer `pending`

2021-12-31 15:14 UTC, mlipok reviewed
please check it

2021-12-31 20:41 UTC, Danp2 commented on wd_helper.au3
>  		$sResponse = _WD_ExecuteScript($sSession, $sScript1, $sParams)
Yes, I had considered adding additional error checking in relation to the calls to _WD_ExecuteScript. However, the idea was to also check for the JSON function returning an error as well if it doesn't find the designated node.

2021-12-31 20:53 UTC, Danp2 reviewed
Please take a look at the latest commit.

2021-12-31 21:57 UTC, mlipok commented
> Please take a look at the latest commit.

Sure in next year... ;)

2022-01-01 18:46 UTC, mlipok commented
Now it's your turn @Danp2

2022-01-01 20:03 UTC, Danp2 approved these changes

2022-01-01 20:11 UTC, Danp2 reviewed
RE: https://github.com/Danp2/WebDriver/pull/114/commits/36c8e6c94416fb1c021e631922d698802c8bbefa

AFAICS, this update doesn't fix or improve the functionality of the script. Seems like it's more of a coding style difference to me. 🙄

2022-01-01 20:22 UTC, mlipok commented
> this update doesn't fix or improve the functionality of the script. Seems like it's more of a coding style difference to me.

almost yes, I also add comment to the code

2022-01-01 20:29 UTC, mlipok commented
currently all this following snippets:

```
		If @error Then
			$iErr = $_WD_ERROR_RetValue
			ExitLoop
		EndIf

```
in this function, are placed at the same indentation.
It tidied up the loop processing a bit.

2022-01-01 20:33 UTC, mlipok commented
Now it looks even better, so the code is easier to understand and maintain.
At least I hope so.

2022-01-01 20:53 UTC, Danp2 approved these changes

2022-01-01 20:55 UTC, merged