wd_core.au3 - $_WD_DefaultTimeout - not const
Danp2/WebDriver pull request #83
Opened 2021-07-25 20:05 UTC by mlipok

User should be able to adjust this default value.
I can imagine that someone has a very poor connection and is doing a project, e.g. got a freelancer contract, and now has to adjust to a slower connection.

2021-07-26 12:02 UTC, Danp2 requested changes
The user can currently override the default timeout by providing the new value for each relevant function call. However, I can see where this would have value as well.

This update will require a few additional changes --

- Move the line to the correct region (global constant vs global variable)
- Update _WD_Option to allow the user to retrieve / set the default timeout

2021-07-26 19:31 UTC, mlipok commented
give me one week... I'm on vacation.

2021-07-26 19:44 UTC, mlipok commented
I had time for creativity, please review

2021-07-27 20:43 UTC, Danp2 approved these changes

2021-07-27 20:44 UTC, merged